baseURL: https://emiliemanolas.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Let's Go!
    subtitle: |-
      Welcome to my website, an introduction my story, my passions and some of my works. 
      Ready to discover more about me?
    title: Hey it's Emilie!
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regent's Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: emanolas.mfa2022@london.edu
        title: Email
    enable: yes
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: emilielbs
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/emilie_manolas/
      - icon: fa-github
        label: GitHub
        url: https://github.com/emiliemanolas
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/emilie-manolas/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Curious?
        url: blogs
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/ipsum
      - name: My Passions
        url: blogs
      - name: My Game
        url: elements.html
      - name: Blogs
        url: blogs
    menu: Menu
    subtitle: Portfolio Website
    title: EMILIE MANOLAS
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: My Story
        title: About Me
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Tavelling & Horseriding
        title: My Passions
        url: blogs/tempus
      - image: TfL.jpg
        subtitle: Solving the mystery of May & June 2020
        title: TfL Bike Sharing
        url: blogs/tfl
      - image: TfL.jpg
        subtitle: Who's the best?
        title: Spielberg vs Burton
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: A case study of China's, France's and the US' GDP
        title: Cracking GDP Composition
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: My Fabulous Game
        title: Terraria
        url: blogs/ipsum
  two:
    buttonText: Let's Go!
    enable: yes
    subtitle: "Hi there!
      \r\n    If you want to get to know me you're in the right place! \r\n    I will tell you my story, give you an overview of my ambitions
      where I grew up, lived and studied. You'll also have the opportunity to discover my passions.
      \r\n    Wait that's not all! You'll also get the chance to see some of my work on R and Python!
      \r\n    Exciting right? ;)."
    title: My Story
    url: blogs
